### ISSUE TITLE
Problem with self closing tags

### ISSUE THREAD

**Issue by dmmz** [saebekassebil/musicjson#1]
&lt;A\ &gt;
&lt;B &gt;hello&lt;/B &gt;

is translated to:

{
A: {B: "hello"}
}

it should be somthing like:

{ 
A:{},
B:"hello"
}

**Comment by saebekassebil** [comment]
Hey @dmmz and thanks for reporting! This was a bug in the XML parser I used - I've now ported the code to [sax-js](https://github.com/isaacs/sax-js) which seems to work. Let me know if you experience any further problems!
